;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname HW05Stub) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define smallE '(or (and x y)
                    (or (and x (not y))
                        (or (and (not x) y)
                            (and (not x) (not y))))))

(check-expect (reduce smallE) true)

(define smallE2 '(or 
                  (or (and x (not y))
                      (or (and (not x) y)
                          (and (not x) (not y))))
                  (and x y)))

(check-expect (reduce smallE2) true)

(define midE
  '(or (and   v   (and   w   (and   x   (and   y     z  ))))
       (or (and   v   (and   w   (and   x   (and   y   (not z)))))
           (or (and   v   (and   w   (and   x   (and (not y)   z  ))))
               (or (and   v   (and   w   (and   x   (and (not y) (not z)))))
                   (or (and   v   (and   w   (and (not x) (and   y     z  ))))
                       (or (and   v   (and   w   (and (not x) (and   y   (not z)))))
                           (or (and   v   (and   w   (and (not x) (and (not y)   z  ))))
                               (or (and   v   (and   w   (and (not x) (and (not y) (not z)))))
                                   (or (and   v   (and (not w) (and   x   (and   y     z  ))))
                                       (or (and   v   (and (not w) (and   x   (and   y   (not z)))))
                                           (or (and   v   (and (not w) (and   x   (and (not y)   z  ))))
                                               (or (and   v   (and (not w) (and   x   (and (not y) (not z)))))
                                                   (or (and   v   (and (not w) (and (not x) (and   y     z  ))))
                                                       (or (and   v   (and (not w) (and (not x) (and   y   (not z)))))
                                                           (or (and   v   (and (not w) (and (not x) (and (not y)   z  ))))
                                                               (or (and   v   (and (not w) (and (not x) (and (not y) (not z)))))
                                                                   (or (and (not v) (and   w   (and   x   (and   y     z  ))))
                                                                       (or (and (not v) (and   w   (and   x   (and   y   (not z)))))
                                                                           (or (and (not v) (and   w   (and   x   (and (not y)   z  ))))
                                                                               (or (and (not v) (and   w   (and   x   (and (not y) (not z)))))
                                                                                   (or (and (not v) (and   w   (and (not x) (and   y     z  ))))
                                                                                       (or (and (not v) (and   w   (and (not x) (and   y   (not z)))))
                                                                                           (or (and (not v) (and   w   (and (not x) (and (not y)   z  ))))
                                                                                               (or (and (not v) (and   w   (and (not x) (and (not y) (not z)))))
                                                                                                   (or (and (not v) (and (not w) (and   x   (and   y     z  ))))
                                                                                                       (or (and (not v) (and (not w) (and   x   (and   y   (not z)))))
                                                                                                           (or (and (not v) (and (not w) (and   x   (and (not y)   z  ))))
                                                                                                               (or (and (not v) (and (not w) (and   x   (and (not y) (not z)))))
                                                                                                                   (or (and (not v) (and (not w) (and (not x) (and   y     z  ))))
                                                                                                                       (or (and (not v) (and (not w) (and (not x) (and   y   (not z)))))
                                                                                                                           (or (and (not v) (and (not w) (and (not x) (and (not y)   z  ))))
                                                                                                                               (and (not v) (and (not w) (and (not x) (and (not y) (not z)))))))))))))))))))))))))))))))))))))


(check-expect (reduce midE) true)

(define bigE
'(or (and   u   (and   v   (and   w   (and   x   (and   y     z  )))))
(or (and   u   (and   v   (and   w   (and   x   (and   y   (not z))))))
(or (and   u   (and   v   (and   w   (and   x   (and (not y)   z  )))))
(or (and   u   (and   v   (and   w   (and   x   (and (not y) (not z))))))
(or (and   u   (and   v   (and   w   (and (not x) (and   y     z  )))))
(or (and   u   (and   v   (and   w   (and (not x) (and   y   (not z))))))
(or (and   u   (and   v   (and   w   (and (not x) (and (not y)   z  )))))
(or (and   u   (and   v   (and   w   (and (not x) (and (not y) (not z))))))
(or (and   u   (and   v   (and (not w) (and   x   (and   y     z  )))))
(or (and   u   (and   v   (and (not w) (and   x   (and   y   (not z))))))
(or (and   u   (and   v   (and (not w) (and   x   (and (not y)   z  )))))
(or (and   u   (and   v   (and (not w) (and   x   (and (not y) (not z))))))
(or (and   u   (and   v   (and (not w) (and (not x) (and   y     z  )))))
(or (and   u   (and   v   (and (not w) (and (not x) (and   y   (not z))))))
(or (and   u   (and   v   (and (not w) (and (not x) (and (not y)   z  )))))
(or (and   u   (and   v   (and (not w) (and (not x) (and (not y) (not z))))))
(or (and   u   (and (not v) (and   w   (and   x   (and   y     z  )))))
(or (and   u   (and (not v) (and   w   (and   x   (and   y   (not z))))))
(or (and   u   (and (not v) (and   w   (and   x   (and (not y)   z  )))))
(or (and   u   (and (not v) (and   w   (and   x   (and (not y) (not z))))))
(or (and   u   (and (not v) (and   w   (and (not x) (and   y     z  )))))
(or (and   u   (and (not v) (and   w   (and (not x) (and   y   (not z))))))
(or (and   u   (and (not v) (and   w   (and (not x) (and (not y)   z  )))))
(or (and   u   (and (not v) (and   w   (and (not x) (and (not y) (not z))))))
(or (and   u   (and (not v) (and (not w) (and   x   (and   y     z  )))))
(or (and   u   (and (not v) (and (not w) (and   x   (and   y   (not z))))))
(or (and   u   (and (not v) (and (not w) (and   x   (and (not y)   z  )))))
(or (and   u   (and (not v) (and (not w) (and   x   (and (not y) (not z))))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and   y     z  )))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and   y   (not z))))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and (not y)   z  )))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and (not y) (not z))))))
(or (and (not u) (and   v   (and   w   (and   x   (and   y     z  )))))
(or (and (not u) (and   v   (and   w   (and   x   (and   y   (not z))))))
(or (and (not u) (and   v   (and   w   (and   x   (and (not y)   z  )))))
(or (and (not u) (and   v   (and   w   (and   x   (and (not y) (not z))))))
(or (and (not u) (and   v   (and   w   (and (not x) (and   y     z  )))))
(or (and (not u) (and   v   (and   w   (and (not x) (and   y   (not z))))))
(or (and (not u) (and   v   (and   w   (and (not x) (and (not y)   z  )))))
(or (and (not u) (and   v   (and   w   (and (not x) (and (not y) (not z))))))
(or (and (not u) (and   v   (and (not w) (and   x   (and   y     z  )))))
(or (and (not u) (and   v   (and (not w) (and   x   (and   y   (not z))))))
(or (and (not u) (and   v   (and (not w) (and   x   (and (not y)   z  )))))
(or (and (not u) (and   v   (and (not w) (and   x   (and (not y) (not z))))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and   y     z  )))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and   y   (not z))))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and (not y)   z  )))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and (not y) (not z))))))
(or (and (not u) (and (not v) (and   w   (and   x   (and   y     z  )))))
(or (and (not u) (and (not v) (and   w   (and   x   (and   y   (not z))))))
(or (and (not u) (and (not v) (and   w   (and   x   (and (not y)   z  )))))
(or (and (not u) (and (not v) (and   w   (and   x   (and (not y) (not z))))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and   y     z  )))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and   y   (not z))))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and (not y)   z  )))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and (not y) (not z))))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and   y     z  )))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and   y   (not z))))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and (not y)   z  )))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and (not y) (not z))))))
(or (and (not u) (and (not v) (and (not w) (and (not x) (and   y     z  )))))
(or (and (not u) (and (not v) (and (not w) (and (not x) (and   y   (not z))))))
(or (and (not u) (and (not v) (and (not w) (and (not x) (and (not y)   z  )))))
   (and (not u) (and (not v) (and (not w) (and (not x) (and (not y) (not z))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
)

(check-expect (reduce bigE) true)

(define bigE1
'(or (and   u   (and   v   (and   w   (and   x   (and   y   (not z))))))
(or (and   u   (and   v   (and   w   (and   x   (and (not y)   z  )))))
(or (and   u   (and   v   (and   w   (and   x   (and (not y) (not z))))))
(or (and   u   (and   v   (and   w   (and (not x) (and   y     z  )))))
(or (and   u   (and   v   (and   w   (and (not x) (and   y   (not z))))))
(or (and   u   (and   v   (and   w   (and (not x) (and (not y)   z  )))))
(or (and   u   (and   v   (and   w   (and (not x) (and (not y) (not z))))))
(or (and   u   (and   v   (and (not w) (and   x   (and   y     z  )))))
(or (and   u   (and   v   (and (not w) (and   x   (and   y   (not z))))))
(or (and   u   (and   v   (and (not w) (and   x   (and (not y)   z  )))))
(or (and   u   (and   v   (and (not w) (and   x   (and (not y) (not z))))))
(or (and   u   (and   v   (and (not w) (and (not x) (and   y     z  )))))
(or (and   u   (and   v   (and (not w) (and (not x) (and   y   (not z))))))
(or (and   u   (and   v   (and (not w) (and (not x) (and (not y)   z  )))))
(or (and   u   (and   v   (and (not w) (and (not x) (and (not y) (not z))))))
(or (and   u   (and (not v) (and   w   (and   x   (and   y     z  )))))
(or (and   u   (and (not v) (and   w   (and   x   (and   y   (not z))))))
(or (and   u   (and (not v) (and   w   (and   x   (and (not y)   z  )))))
(or (and   u   (and (not v) (and   w   (and   x   (and (not y) (not z))))))
(or (and   u   (and (not v) (and   w   (and (not x) (and   y     z  )))))
(or (and   u   (and (not v) (and   w   (and (not x) (and   y   (not z))))))
(or (and   u   (and (not v) (and   w   (and (not x) (and (not y)   z  )))))
(or (and   u   (and (not v) (and   w   (and (not x) (and (not y) (not z))))))
(or (and   u   (and (not v) (and (not w) (and   x   (and   y     z  )))))
(or (and   u   (and (not v) (and (not w) (and   x   (and   y   (not z))))))
(or (and   u   (and (not v) (and (not w) (and   x   (and (not y)   z  )))))
(or (and   u   (and (not v) (and (not w) (and   x   (and (not y) (not z))))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and   y     z  )))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and   y   (not z))))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and (not y)   z  )))))
(or (and   u   (and (not v) (and (not w) (and (not x) (and (not y) (not z))))))
(or (and (not u) (and   v   (and   w   (and   x   (and   y     z  )))))
(or (and (not u) (and   v   (and   w   (and   x   (and   y   (not z))))))
(or (and (not u) (and   v   (and   w   (and   x   (and (not y)   z  )))))
(or (and (not u) (and   v   (and   w   (and   x   (and (not y) (not z))))))
(or (and (not u) (and   v   (and   w   (and (not x) (and   y     z  )))))
(or (and (not u) (and   v   (and   w   (and (not x) (and   y   (not z))))))
(or (and (not u) (and   v   (and   w   (and (not x) (and (not y)   z  )))))
(or (and (not u) (and   v   (and   w   (and (not x) (and (not y) (not z))))))
(or (and (not u) (and   v   (and (not w) (and   x   (and   y     z  )))))
(or (and (not u) (and   v   (and (not w) (and   x   (and   y   (not z))))))
(or (and (not u) (and   v   (and (not w) (and   x   (and (not y)   z  )))))
(or (and (not u) (and   v   (and (not w) (and   x   (and (not y) (not z))))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and   y     z  )))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and   y   (not z))))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and (not y)   z  )))))
(or (and (not u) (and   v   (and (not w) (and (not x) (and (not y) (not z))))))
(or (and (not u) (and (not v) (and   w   (and   x   (and   y     z  )))))
(or (and (not u) (and (not v) (and   w   (and   x   (and   y   (not z))))))
(or (and (not u) (and (not v) (and   w   (and   x   (and (not y)   z  )))))
(or (and (not u) (and (not v) (and   w   (and   x   (and (not y) (not z))))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and   y     z  )))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and   y   (not z))))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and (not y)   z  )))))
(or (and (not u) (and (not v) (and   w   (and (not x) (and (not y) (not z))))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and   y     z  )))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and   y   (not z))))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and (not y)   z  )))))
(or (and (not u) (and (not v) (and (not w) (and   x   (and (not y) (not z))))))
(or (and (not u) (and (not v) (and (not w) (and (not x) (and   y     z  )))))
(or (and (not u) (and (not v) (and (not w) (and (not x) (and   y   (not z))))))
(or (and (not u) (and (not v) (and (not w) (and (not x) (and (not y)   z  )))))
   (and (not u) (and (not v) (and (not w) (and (not x) (and (not y) (not z))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

(reduce bigE1)